config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "events#index"
  get '/user' => "users#welcome", :as => :user_root
  
  resources :users, only: [:show]
  resources :events
  resources :attendance_records, only: [:create, :destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
  validates_uniqueness_of :attended_event, scope: [:attendee]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendance_records
  has_many :attendees, class_name: "User", :through => :attendance_records
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendance_records
  has_many :attended_events, foreign_key: "attendee_id", class_name: "Event", :through => :attendance_records
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_records_controller.rb
class AttendanceRecordsController < ApplicationController
  def new
    @attendance_record = AttendanceRecord.new
  end
 
  def create
    @attendance_record = AttendanceRecord.new(attendance_record_params)
    @test = "test"
    @attendance_record.user_id = current_user.id.to_i
    @attendance_record.event_id = attendance_record_params[:attended_event_id]
    if @attendance_record.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end 
 end
 
 def destroy
  @attendance_record = AttendanceRecord.find(params[:id])
  @attendance_record.destroy
    
  redirect_to request.referrer, status: :see_other
 end

 private
 def attendance_record_params
  params.require(:attendance_record).permit(:attendee_id, :attended_event_id) 
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
 
  def index
    @events = Event.all
    @all_attendance_records = AttendanceRecord.all
    @new_attendance_record = AttendanceRecord.new
  end

  def show
    @event = Event.find(params[:id])
 
  end
  
  def new
    @event = Event.new 
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
    @event = Event.find(params[:id])
  end

  def update 
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    
    redirect_to root_path, status: :see_other
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :location, :time)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def welcome
    @user = User.find(current_user.id)
    @all_attendance_records = AttendanceRecord.all
  end 
  def show
    if params[:id].to_i == current_user.id
      redirect_to action: "welcome"
    else
      @user = User.find(params[:id])
      @all_attendance_records = AttendanceRecord.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendance_records/new.html.erb
<h1>New Attendance Record</h1>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @event.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %><br>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> 
   
     <div>
    <%= form.label :time %><br>
    <%= form.datetime_select :time %><br>
    <% @event.errors.full_messages_for(:time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> 
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<div id="events">
  <h1>All Events</h1>
  <div class="d-flex flex-wrap gap-2">
    <% @events.each do |event| %>
      <%= render 'shared/event_card', event: event, all_attendance_records: @all_attendance_records, new_attendance_record: @new_attendance_record%>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title =%></h1>

<p><%= @event.description =%></p>

<ul>
<% if current_user.id == @event.creator_id %>
  <li>
    <%=link_to "Edit", edit_event_path(@event)%>
  </li>
  <li>
  <li>
    <%=link_to "Destroy", event_path(@event), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </li>
<% end %>
<h2>Attending</h2>
<% if @event.attendees.nil? %>
<p>Current No Attendees</p>
<% else %>
<ul>
<% @event.attendees.each do |attendee| %>
<li><%= User.find(attendee.id).email %></li>
<% end %>
</ul>
<% end %>
  <li>
    <%=link_to "Home", events_path %>
  </li>
</ul>

app/views/layouts/_alert.html.erb
  <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Private Events</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"> <%= link_to "My Events", user_path(current_user.id), class: "nav-link" %></li>
          <li class="nav-item">
            <%= link_to "Add New Event", new_event_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
   <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%=  render 'layouts/navbar' %>
    <%= render 'layouts/notice' %>
    <%= render 'layouts/alert' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_event_card.html.erb
<%# Dynamic Card Styling %>
<% @card_classes = "card border border-4" %>
<% if user_signed_in? then @card_classes = "card border border-primary border-4" end%>
  <% if user_signed_in? && current_user.id.to_i == event.creator_id.to_i then @card_classes = "card border border-success border-4" end%>
    <div class="<%=@card_classes%> " style="width: 300px">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.time%></h6>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
        <p class="card-text"><%= event.description %></p>
        <p>Number of Guests: <%= p event.attendees.count %></p>
      </div>
      <% if user_signed_in? %>
        <div class="d-flex gap-2 card-footer">
          <%=link_to "View Details", event_path(event.id), :class => 'btn btn-secondary' %>
          <% if !(current_user.id.to_i == event.creator_id.to_i) && !event.attendees.includes(User.find(current_user.id)).exists? %>
            <%= form_with model: @new_attendance_record do |form| %>
              <%= form.hidden_field :attendee_id, value: current_user.id %>
              <%= form.hidden_field :attended_event_id, value: event.id %>
              <%= form.submit "Attend", class: "btn btn-primary" %>
            <% end %>
          <% elsif  !event.attendees.where(:id => current_user.id).first.nil? %>
            <%= link_to "Cancel RSVP", attendance_record_path(@all_attendance_records.where(:event_id => event.id, :user_id => current_user.id).first[:id]),
      data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    }, class: "btn btn-danger" %>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/users/show.html.erb
<h2><%= @user.email %>'s Events</h2>
<div class="d-flex gap-4">
  <% @user.created_events.each do |event| %>
    <%= render 'shared/event_card', event: event %>
  <% end %>
</div>

app/views/users/welcome.html.erb
<h2>My Events</h2>
<div class="d-flex gap-4">
  <% @user.created_events.each do |event| %>
    <%= render 'shared/event_card', event: event %>
  <% end %>
</div>
<h2>Upcoming Events</h2>
<div class="d-flex gap-4">
  <% @user.attended_events.each do |event| %>
    <%= render 'shared/event_card', event: event %>
  <% end %>
</div>